# Generated by Django 5.2.8 on 2026-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodreport',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('warning', 'Awaiting Confirmation'), ('expired', 'Expired')], default='live', max_length=10),
        ),
    ]
